### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Chen-Hu** [xiaosimao/AiSpider#1]
遇到了这个问题
我的环境 ubuntu
python -V  Python 3.6.2
pip -V  pip 9.0.1

pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
Collecting pymongo==3.4.0 (from -r requirements.txt (line 1))
  Using cached pymongo-3.4.0.tar.gz
Collecting pybloom==1.1 (from -r requirements.txt (line 2))
  Using cached pybloom-1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-z7mcccyz/pybloom/setup.py", line 2, in <module>
        from ez_setup import use_setuptools
      File "/tmp/pip-build-z7mcccyz/pybloom/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-z7mcccyz/pybloom/

**Comment by xiaosimao** [comment]
你好，这个应该是pybloom在python3版本的安装问题，可以参考一下这个：http://download.csdn.net/download/a1368783069/9597338
