### ISSUE TITLE
framework-test has something wrong

### ISSUE THREAD

**Issue by alexanderhawl** [xiaosimao/AiSpider#4]
Exception in thread Thread-30 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/root/Desktop/sqlmapproxyip/AiSpider/spider/threads.py", line 36, in get_work_queue
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'empty'
Exception in thread Thread-29 (most likely raised during interpreter shutdown):Exception in thread Thread-2 (most likely raised during interpreter shutdown):Exception in thread Thread-86 (most likely raised during interpreter shutdown):

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_innerTraceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

  File "/usr/lib/python2.7/threading.py", line 754, in run  File "/usr/lib/python2.7/threading.py", line 754, in run

**Comment by zhuhelei** [comment]
I have the same problem

**Comment by xiaosimao** [comment]
两位好,这个问题是在程序结束的时候,多线程回收的问题,但是不影响数据的采集,这个我会修复一下.
